# Generated by Django 5.0.2 on 2024-04-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltellapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('works', models.CharField(max_length=100)),
                ('perhour', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
    ]
