# Generated by Django 5.0.2 on 2024-04-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eltellapp', '0002_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='rate',
            new_name='experience',
        ),
    ]
