# Generated by Django 5.0.4 on 2024-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltellapp', '0004_app_logo_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=254, upload_to=None)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
